[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.1"
futures-util = "0.3.30"
lazy_static = "1.5.0"
portable-pty = "0.8.1"
ratatui = "0.27.0"
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.38.1", features = ["full"] }
tokio-tungstenite = "0.23.1"
tui-term = "0.1.12"
common = { path = "../common" }
serde_json = "1.0.120"
uuid = "1.10.0"
rand = "0.8.5"
fake = "2.9.2"
urlencoding = "2.1.3"
