[package]
name = "client"
version = "0.1.0"
edition = "2021"

[features]
audio = ["dep:rodio"]

[dependencies]
anyhow = "1.0.86"
bytes = "1.7.1"
common = { path = "../common", features = ["client"] }
futures-util = "0.3.30"
lazy_static = "1.5.0"
portable-pty = "0.8.1"
rand = "0.8.5"
ratatui = "0.28.0"
reqwest = "0.12.5"
rodio = { version = "0.19.0", optional = true }
serde = { workspace = true }
serde_json = "1.0.124"
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.38.1", features = ["full"] }
tokio-tungstenite = "0.23.1"
toml = "0.8.19"
tui-term = "0.1.13"
uuid = "1.10.0"
