[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio-tungstenite = "0.23.1"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
