name: Delete review package

on:
  pull_request:
    types: [ closed ]

jobs:
  delete-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - name: Get package version ID by tag
        id: get_package_version
        run: |
          repo="tomgroenwoldt/keyglide"
          package_name="keyglide-service"
          tag="${{ steps.meta.outputs.tags }}"
          
          # Get package version ID by tag
          version_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/tomgroenwoldt/packages/container/keyglide-service/versions" \
            | jq -r ".[] | select(.metadata.container.tags[] == \"$tag\") | .id")

          echo "Version ID: $version_id to be deleted"

      - name: Delete package version
        if: steps.get_package_version.outputs.version_id != ''
        run: |
          version_id=${{ steps.get_package_version.outputs.version_id }}
          
          # Delete the package version using GitHub API
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/orgs/tomgroenwoldt/packages/container/keyglide-service/versions/$version_id"

