name: Delete review package on closed PR

on:
  pull_request:
    types: [closed]

jobs:
  delete_image:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to get access to branch name and other metadata
    - name: Checkout repository
      uses: actions/checkout@v3

    # Get repository and branch name for the Docker image tag
    - name: Set image name and tag
      id: set_image_name
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}:${{ github.head_ref }}"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    # Delete the Docker image from GHCR
    - name: Delete Docker image from GHCR
      run: |
        IMAGE_NAME=${{ env.IMAGE_NAME }}
        echo "Deleting image $IMAGE_NAME from GHCR..."
        # Extract image name and version (without repository)
        IMAGE_PATH="${IMAGE_NAME##*/}"
        IMAGE_VERSION="${IMAGE_PATH##*:}"

        # GitHub API URL for deleting the image version
        DELETE_URL="https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${IMAGE_PATH%%:*}/versions"

        # Get all versions of the image and find the version ID
        IMAGE_VERSION_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "$DELETE_URL" | jq -r '.[] | select(.metadata.container.tags[] == "'$IMAGE_VERSION'") | .id')

        if [ -z "$IMAGE_VERSION_ID" ]; then
          echo "Image version not found."
          exit 1
        fi

        # Delete the image version
        curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             "$DELETE_URL/$IMAGE_VERSION_ID"

      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}


